### ISSUE TITLE
'Ugly' Scrollbars in Chrome

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#1498]
**Context**

Severity: QOL
Kitsu version: 0.19.43

**Describe the bug**

Firefox uses the beautiful, small Vue scrollbars on the Shots page while Chrome seems to fall back to the built in ones.
Probably not a real but but just a 'small' thing.

**Screenshots**

Screenshot from Chrome
![image](https://github.com/user-attachments/assets/1b0d82bb-8eb0-4ca6-aa7f-5aad9a1d1dc6)

Similar area in firefox
![image](https://github.com/user-attachments/assets/89609318-31cd-4d7d-8c09-eb1168c7f7f8)

Same in Edge for referwence ( but I guess noone uses edge ;) )
![image](https://github.com/user-attachments/assets/2f8d38e9-b9f3-40c9-967e-34548e79bed5)

**Desktop (please complete the following information):**

 - OS: Windows 11/10
 - Browser Chrome
 - Version 126.0.6478.183

**Comment by tetsuoanimation** [comment]
Adding this to the main css as an override seems to style them more firefox like. My example probably has the wrong colours:

```css
::-webkit-scrollbar {
  width: 5px; 
  height: 5px;
}
::-webkit-scrollbar-track {
  background: #0000; /* Track color */
}
::-webkit-scrollbar-corner {
  background: #0000
}

::-webkit-scrollbar-thumb {
  background: #666; /* Thumb color */
  border-radius: 2.5px; /* Thumb border-radius */
}

::-webkit-scrollbar-thumb:hover {
  background: #555; /* Hover thumb color */
}
::-webkit-scrollbar-thumb:active {
  background: #444; /* Active thumb color */
}
```
